name: Node.js CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./p03tdw/node_modules  # Atualizado para refletir o caminho correto
          key: ${{ runner.os }}-node-${{ hashFiles('p03tdw/package-lock.json') }} # Atualizado para refletir o caminho correto

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: List files in working directory
        run: ls -la ./p03tdw # Atualizado para refletir o caminho correto

      - name: Install dependencies
        run: npm install
        working-directory: ./p03tdw # Atualizado para refletir o caminho correto

      - name: Build the project
        run: npm run build --if-present
        working-directory: ./p03tdw # Atualizado para refletir o caminho correto

      - name: Run tests
        run: npm test
        working-directory: ./p03tdw # Atualizado para refletir o caminho correto
