name: Node.js CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./tdwP03/p03tdw/node_modules  # Caminho correto para node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('tdwP03/p03tdw/package-lock.json') }} # Caminho correto para package-lock.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: ./tdwP03/p03tdw # Caminho correto para p03tdw

      - name: Build the project
        run: npm run build --if-present
        working-directory: ./tdwP03/p03tdw # Caminho correto para p03tdw

      - name: Run tests
        run: npm test
        working-directory: ./tdwP03/p03tdw # Caminho correto para p03tdw
